### PR TITLE
Home page mockup #6

### PR DESCRIPTION
**Pull request by luisvillara**
Use README.md to run the project, it is necessary to use Docker

### CODE REVIEW

**Comment by isysd** [comment]
It doesn't seem to build properly due to:

`npm ERR! Error: Invalid name: "Tigo CTM"`

**Comment by isysd** [comment]
I'm not able to actually run this to see the files, due to build errors, nor are they in the format requested. There is no way we can accept this.

**Comment by luisvillara** [comment]
I'm very sorry! But this is not extra crap and you are wrong when you said "gigabytes of extra stuff". Look, I'll make whatever you want but I'm not share your thoughts about Docker, if you don't understand why I used I'm ok with that. It's ok that you don't understand that, but, like I said, I'm a professional and I'll make whatever you want. Please wait for another pull request soon. Thank you!

**Comment by isysd** [comment]
I'm not questioning your abilities, @luisvillara. I realize lots of people use Docker, but it doesn't belong in a github repo. I really did download gigabytes of things trying to run this. :(

**Comment by luisvillara** [comment]
It's all good @isysd, lets do this work! 👍

**Comment by isysd** [comment]
To be clear @luisvillara, gulp is also included in the "shouldn't be required" camp. This is a very simple site that we plan to build and host statically. If something can't simply be imported, we probably don't want it.

**Pull request closed without merging**
